In [108]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler ,LabelEncoder
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedShuffleSplit,train_test_split
from sklearn.metrics import  accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
import numpy as np
from wifi import Cell

    TODO:  Remover rede NET-CLARO-WIFI
           Remover redes de celular

 ## Estrutura Dataset

| RedeA 	| RedeB 	| RedeC 	| classe 	|
|:-----:	|:-----:	|:-----:	|:------:	|
|   40  	|   70  	|   20  	| quarto 	|
|   85  	|   65  	|   0   	|  sala  	|

In [109]:
wifis = pd.read_csv('../data/dataset.csv')
x = wifis.drop('classe', axis=1)
x = x.drop(['FARMA POPULAR','#NET-CLARO-WIFI','Unnamed: 30','moto g(6) plus 3609', 'Redmi Note 9S','70mai_Pro Plus+_8eb4'] ,axis=1)
y = wifis['classe']
len(x.columns)

25

In [110]:
y = wifis['classe']
print('claase' not in x.columns)
print(x.columns)
print(x.shape[1])

True
Index(['Espindola_2.4G', 'BEATRIZ', 'NET 2G', 'Oi_93B7',
       'TOPNET 99255-7919 GT SURF', 'ARTHUR', '2G.MIMO.BEBY', 'GVT-53AA',
       'CONVENIENCIA_TORTUGA', 'WIFI GLOBAL 227', 'Galaxy A20s6468',
       '2313_Oi_Fibra', 'Araujo', 'A304_Oi_Fibra 2.4G', 'ViperNet_Salão ',
       'Figueiredo 2.4', 'Salvato', 'CGU-V3208', 'WIFI GLOBAL', 'NICOLAS',
       '@Casadatapioca', 'Parangaricutirimirruaro', 'net-325', 'VIVO-FCA1',
       '732A_Fibra 2 G'],
      dtype='object')
25


In [111]:
std_sacler = StandardScaler()
x_normalize = std_sacler.fit_transform(x)
print("Dados normalizados com sucesso")

Dados normalizados com sucesso


In [112]:
 ## Fase 3 (peso 2): Treino e ajuste de parâmetros.  Utilizando o conjunto de validação, encontre o melhor  conjunto de parâmetros para o seu problema. Vc pode utilizar a quantidade de vizinhos, diferentes valores de p, pesos, etc.


In [116]:
sss = StratifiedShuffleSplit(n_splits=10, test_size=0.30, train_size=0.7, random_state=0)
lacc = []
melhores_vizinhos = {}
for k in range(2,19):
    model = KNeighborsClassifier(n_neighbors=k)
    for train_index,test_index in sss.split(x_normalize,y):
        xtrain = x_normalize[train_index]
        ytrain = y[train_index]
        xtest  = x_normalize[test_index]
        ytest  = y[test_index]
        x_test,x_validation ,y_test , y_validation = train_test_split(xtest, ytest, test_size=0.5, random_state=0)
        model.fit(x_validation,y_validation)
        ypred=model.predict(x_test)
        acc = accuracy_score(y_test,ypred)
        print("Precision Score : ",precision_score(y_test,ypred, average='micro'))
        print("Recall Score : ",recall_score(y_test,ypred,average='micro'))
        print("f1 Score : ",f1_score(y_test,ypred,average='micro'))
        print(f'{confusion_matrix(y_test,ypred)}')
        print(f'accuracy_score {acc} para numero de vizinhos {k} ')
        lacc.append(acc)
        media = np.mean(lacc)
        desvio_padrao = np.std(lacc)
        f1_score_para_k = f1_score(y_test,ypred,average='micro')
    melhores_vizinhos[f1_score_para_k] = (k, desvio_padrao, media)
    print("qtd_vizinhos: %2d , Média: %4.3f Std: %4.3f " % (k,media, desvio_padrao) )
    f1_melhor_vizinho = max(melhores_vizinhos)
    melhor_vizinho = melhores_vizinhos[f1_melhor_vizinho]
    print('melhor quantidade de vizinhos:',melhor_vizinho[0],',media:', melhor_vizinho[2],',desvio padrao:',melhor_vizinho[1])
    print(f"Média: %4.3f Std: %4.3f para {k} vizinhos "%(np.mean(lacc),np.std(lacc)))
    print('_____________________________________________________________________________________________________________________________________')

Precision Score :  0.8
Recall Score :  0.8
f1 Score :  0.8000000000000002
[[2 1 1 0 0]
 [0 4 0 0 0]
 [1 0 5 0 0]
 [0 0 1 2 0]
 [0 0 0 0 3]] matrix
accuracy_score 0.8 para numero de vizinhos 2 
Precision Score :  0.4
Recall Score :  0.4
f1 Score :  0.4000000000000001
[[2 0 0 0 0]
 [1 2 0 0 0]
 [3 2 3 0 0]
 [0 0 0 1 0]
 [1 4 1 0 0]] matrix
accuracy_score 0.4 para numero de vizinhos 2 
Precision Score :  0.65
Recall Score :  0.65
f1 Score :  0.65
[[0 4 0 0 0]
 [0 2 0 0 0]
 [2 0 5 0 0]
 [0 0 0 2 0]
 [0 1 0 0 4]] matrix
accuracy_score 0.65 para numero de vizinhos 2 
Precision Score :  0.55
Recall Score :  0.55
f1 Score :  0.55
[[3 0 0 0 0]
 [0 3 0 0 0]
 [1 3 3 0 0]
 [1 0 0 2 0]
 [0 4 0 0 0]] matrix
accuracy_score 0.55 para numero de vizinhos 2 
Precision Score :  0.85
Recall Score :  0.85
f1 Score :  0.85
[[1 0 0 0 0]
 [0 4 1 0 0]
 [0 0 6 0 0]
 [1 1 0 3 0]
 [0 0 0 0 3]] matrix
accuracy_score 0.85 para numero de vizinhos 2 
Precision Score :  0.35
Recall Score :  0.35
f1 Score :  0.35
[[1 0 

## PARA MELHOR NUMERO DE VIZINHOS ACAHDOS ANTERIORMENTE NA CELULA ACIMA


In [114]:
print("PARA MELHOR NUMERO DE VIZINHOS ACAHDOS ANTERIORMENTE NA CELULA ACIMA")
sss = StratifiedShuffleSplit(n_splits=10, test_size=0.30, random_state=0)
lacc = []
model = KNeighborsClassifier(n_neighbors=melhor_vizinho[0])
for train_index,test_index in sss.split(x_normalize,y):
    xtrain = x_normalize[train_index]
    ytrain = y[train_index]
    xtest  = x_normalize[test_index]
    ytest  = y[test_index]
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    acc = accuracy_score(ytest,ypred)
    print("Precision Score : ",precision_score(ytest,ypred, average='micro'))
    print("Recall Score : ",recall_score(ytest,ypred,average='micro'))
    print("f1 Score : ",f1_score(ytest,ypred,average='micro'))
    print(confusion_matrix(ytest,ypred))
    print(f'accuracy_score {acc} para numero de vizinhos {melhor_vizinho[0]} ')
    lacc.append(acc)
print(f"Média: %4.3f Std: %4.3f para {melhor_vizinho[0]} vizinhos "%(np.mean(lacc),np.std(lacc)))


PARA MELHOR NUMERO DE VIZINHOS ACAHDOS ANTERIORMENTE NA CELULA ACIMA
Precision Score :  0.9024390243902439
Recall Score :  0.9024390243902439
f1 Score :  0.9024390243902439
[[ 5  0  1  0  0]
 [ 1  6  1  0  0]
 [ 0  1 11  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0  8]]
accuracy_score 0.9024390243902439 para numero de vizinhos 1 
Precision Score :  0.8780487804878049
Recall Score :  0.8780487804878049
f1 Score :  0.8780487804878049
[[ 2  1  3  0  0]
 [ 0  8  0  0  0]
 [ 1  0 11  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0  8]]
accuracy_score 0.8780487804878049 para numero de vizinhos 1 
Precision Score :  0.926829268292683
Recall Score :  0.926829268292683
f1 Score :  0.926829268292683
[[ 5  1  0  0  0]
 [ 1  6  1  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0  8]]
accuracy_score 0.926829268292683 para numero de vizinhos 1 
Precision Score :  0.9512195121951219
Recall Score :  0.9512195121951219
f1 Score :  0.9512195121951219
[[ 4  1  1  0  0]
 [ 0  8  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  

     Script para teste do  modelo

In [115]:
# wifi_force = []
# wifis_moment = list(Cell.all('wlp3s0'))
# print(wifis_moment)
# for wifiss in wifis_moment:
#     print(wifiss.frequency)
#     if(str.startswith(wifiss.frequency,'2')):
#         print(wifiss.ssid)
#         quality_clean = str(wifiss.quality).split('/')
#         wifi_force.append(int(quality_clean[0]))
# number_zeros = len(wifi_force) - x.shape[1]
# number_zeros = np.abs(number_zeros)
# array_zeros =  number_zeros * [0]
# wifi_force = wifi_force + array_zeros
# print(wifi_force)
# result = model.predict([wifi_force])
# print(f'O comodo que você está é: {result[0]}')


